Revit Conversion MEP Trades
specklesystems/speckle-sharp pull request #1236
Opened 2022-05-03 11:54 UTC by golembiovskyi

## Description

- Fixes # 977

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

- Manual Tests 

## Docs

2022-06-10 16:01 UTC, teocomi requested changes

2022-06-10 16:01 UTC, teocomi commented on Objects/Objects/BuiltElements/Revit/FamilyInstance.cs
> +        public Connector[] connectors { get; set; }
So instead of adding these properties to FamilyInstance, Let's make a new class that inherits from it!

2022-07-05 11:19 UTC, clairekuang commented on Objects/Objects/BuiltElements/Duct.cs
> +    public RevitDuct(string family, string type, [SchemaMainParam] Line baseLine, string systemName, string systemType, Level level, double width, double height, double diameter, double velocity = 0,
A new constructor needs to be added with the `connectors` argument to not break backwards compatibility with existing GH components

2022-07-05 11:19 UTC, clairekuang commented on Objects/Objects/BuiltElements/Duct.cs
> +    public RevitFlexDuct(string family, string type, [SchemaMainParam] ICurve baseCurve, string systemName, string systemType, Level level, double width, double height, double diameter, Vector startT
A new constructor needs to be added with the `connectors` argument to not break backwards compatibility with existing GH components

2022-07-05 11:19 UTC, clairekuang commented on Objects/Objects/BuiltElements/Pipe.cs
> +    public RevitPipe(string family, string type, [SchemaMainParam] ICurve baseCurve, double diameter, Level level, string systemName = "", string systemType = "", List<Parameter> parameters = null, C
A new constructor needs to be added with the `connectors` argument to not break backwards compatibility with existing GH components

2022-07-05 11:21 UTC, clairekuang commented on Objects/Objects/BuiltElements/Revit/Connector.cs
> +  public class Connector : Base
This class needs scoping review, eg `direction` should probably be a `Vector`

2022-07-05 11:21 UTC, clairekuang commented on Objects/Objects/BuiltElements/Revit/FamilyInstance.cs
> -    public FamilyInstance(Point basePoint, string family, string type, Level level,
A new constructor needs to be added with the new arguments to not break backwards compatibility with existing GH components

2022-07-05 11:22 UTC, clairekuang commented on Objects/Objects/BuiltElements/Revit/RevitMEPCurve.cs
> +  abstract class RevitMEPCurve : Base, IDisplayValue<List<Mesh>>, IConnectable
This should implement `ICurve`

2022-07-05 11:23 UTC, clairekuang commented on Objects/Objects/Geometry/Orientation.cs
> +  public class Orientation : Base
New `Orientation` class is probably not necessary, could use `Plane` or 'Transform` instead depending on the use cases

2022-07-05 11:25 UTC, clairekuang commented on Core/Core/Kits/ISpeckleConverter.cs
> +    public void ConnectElement(ApplicationPlaceholderObject obj, List<ApplicationPlaceholderObject> objects);
Reconsider adding a new binding to converters, as this would require *all* of our converters to implement this

2022-08-10 16:04 UTC, merged