CORE: Fixes `SpecialFolder.ApplicationData` pointing to `Default` user
specklesystems/speckle-sharp pull request #1511
Opened 2022-08-12 09:24 UTC by AlanRynne

Reported in the forum:

We were assuming that `Environment.SpecialFolder.ApplicationData` would always return the correct user path for the **current roaming user**; but this is not the case. For some network users, the path returned is the one for the `Default` user, which is used as a template for new users in windows.

This leads to our KitManager, AccountManager and others to not be able to find the Speckle folder, as they're looking in the wrong place! 😱

**Solution**

After a bit of back and forth we decided to assemble our own **AppData** path by getting the username of the current user and attaching `/AppData/Roaming` at the end.

In order to make this change universal, there are some new helper methods `Helpers.SpeckleFolderPath` being the most important one; this will return the correct speckle folder path, skipping this problem, but also taking into account the install location for users who installed systemwide.

All places where this was in use have been properly updated to use this new helper.

2022-08-14 20:02 UTC, teocomi requested changes
Added inline comments, happy to chat about them.

2022-08-14 20:02 UTC, teocomi commented on Core/Core/Transports/SQLite.cs
> +        basePath = Helpers.CorrectedApplicationDataPath;
See comment for accounts, this should not be shared across users.

2022-08-14 20:02 UTC, teocomi commented on Core/Transports/DiskTransport/DiskTransport.cs
> -        basePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Speckle", "DiskTransportFiles");
See comment for accounts, this should not be shared across users.

2022-08-15 12:51 UTC, AlanRynne commented
I've refactored things a bit. We now have inside `Core.Api.Helpers`:

- `UserApplicationDataPath` returns the %appdata% path for the current user
- `InstallApplicationDataPath` returns the application data folder where speckle was installed (either _appdata_ or _programdata_)
- `InstallSpeckleFolderPath` returns the path to the Speckle installation folder
- `UserSpeckleFolderPath` returns the path to the **users Speckle folder**, were their respective accounts and cache should live.

2022-08-15 13:49 UTC, teocomi approved these changes

2022-08-15 13:50 UTC, merged