Tekla Structures Installer TSEP File
specklesystems/speckle-sharp pull request #1521
Opened 2022-08-16 16:37 UTC by Reynold-Chan

TBD

2022-08-23 09:54 UTC, AlanRynne requested changes
TSEP file should never be committed! Oopsies! 🫢

Lets delete that and add it to gitignore

2022-08-23 09:54 UTC, AlanRynne commented on .circleci/scripts/config-template.yml
> +  build-connector-new: # Reusable job for basic connectors
Now that we have this working, let's try to come up with a more elegant solution than duplicating the entire connector build step.

2022-08-23 09:54 UTC, AlanRynne commented on .circleci/scripts/config-template.yml
> +      - run: # Creates the inno installer
This is basically the step we need to deal with, as everything else is unique :)

Maybe we just copy it over to the build-connector job, and just do some conditional steps to just run it on it's slug.

2022-08-23 13:03 UTC, Reynold-Chan commented
> TSEP file should never be committed! Oopsies! 🫢
> 
> Lets delete that and add it to gitignore

haha yep

2022-08-26 08:08 UTC, AlanRynne approved these changes
YAY! 🥳 It all looks good now

2022-08-26 08:19 UTC, merged