fix(dui): preview issues #1961 #1960
specklesystems/speckle-sharp pull request #1964
Opened 2022-12-01 12:36 UTC by teocomi

Fixes preview issues in DUI: #1961 #1960
A bit hacky but it gets the job done :)

2022-12-01 21:07 UTC, AlanRynne requested changes
Sadly, this only seems to have fixed #1961 but not #1960

![2022-12-01 22 04 09](https://user-images.githubusercontent.com/2316535/205159241-76e2a97d-6bd5-4120-a4ce-185ad251fb4e.gif)

2022-12-05 19:06 UTC, teocomi commented
Thanks for checking @AlanRynne , it should now account for branch changes properly :)

2022-12-06 09:41 UTC, AlanRynne approved these changes

2022-12-06 09:41 UTC, AlanRynne commented
Changes were tested and work as expected 🙌🏼

2022-12-06 09:41 UTC, merged