feat(AdvanceSteel): Converting AS Slab to Speckle
specklesystems/speckle-sharp pull request #2412
Opened 2023-04-11 11:58 UTC by phliberato

## Description & motivation

- Converting Advance Steel Slab object to Speckle
- Organize Speckle objects for Advance Steel into different files

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2023-04-13 17:07 UTC, teocomi requested changes
Thanks, just some minor changes!

2023-04-13 17:07 UTC, teocomi commented on Core/Core/Core - Backup.csproj
this can be removed

2023-04-13 17:07 UTC, teocomi commented on Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/AdvanceSteel/ConverterAutocadCivil.Gratings.cs
> +using System;
We can clean some of these `using`s form this file and the ones below

2023-04-13 17:07 UTC, teocomi commented on Objects/Objects/Objects - Backup.csproj
Can also be removed

2023-04-13 18:39 UTC, phliberato commented
@teocomi I think it´s ok

2023-04-14 12:41 UTC, teocomi approved these changes
Txs!

2023-04-14 12:41 UTC, merged