feature: Adds Pagination to StreamGetBranches and increase limit requested by amend DUI
specklesystems/speckle-sharp pull request #2440
Opened 2023-04-14 23:20 UTC by jsdbroughton

Closes: #2436 

## Description & motivation

Allows for use cases heard from Speckle users requiring more than 100 branches as they address cataloguing or complex team information management. The server allows a maximum of 100 results per query; the current solution takes this as a hard limit.

## Changes:

<!---

### Core / API / GraphQL / Client.BranchOperations :: StreamGetBranches
- Adds pagination to the query

### DUI2 / ViewModels / StreamViewModel
- increases the Branches requested from 100 to 1000.

## Validation of changes:

Rhino and Navisworks both tested against https://speckle.xyz/streams/01fca0eab7

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

2023-04-15 14:11 UTC, AlanRynne requested changes
I would advise against this solution.

The api call should be "pure", meaning it does 1 call when you run it, not potentially 100s. It should be the responsibility of the project using this method to implement pagination on their end.

☝🏼 This would require **adding a cursor input to this call**, which I'd be happy to have.

If this is something commonly done in many connectors, we should create a separate function to get N branches while safely handling all other server considerations, but leave `StreamGetBranches` untouched.

2023-04-15 14:11 UTC, AlanRynne commented on Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.BranchOperations.cs
> +    } while (branches.Count < branchesLimit && nextCursor != null);
This while loop is questionable, depending on the inputs it could hit our rate-limit quite easily.

2023-04-15 14:20 UTC, jsdbroughton commented
That makes sense. I can review. The idea here would be to do that call recursion in DUI. Thanks

2023-04-16 15:14 UTC, teocomi commented
Agree with Alan :)

It also sounds more of a UI/UX problem; how would people deal with 100+ branches in the current DUI?
Or better, how are they planning to use them? This could be pretty informative for DUI3...

2023-04-22 19:49 UTC, jsdbroughton commented
> It also sounds more like a UI/UX problem; how would people deal with 100+ branches in the current DUI?
> Or better, how are they planning to use them? This could be pretty informative for DUI3...

This is a UI/UX problem that exists in both Connectors and the web. The specific use case I have referred to in Notion cc-ing @teocomi 

Aside from the reporting user, we see increasing numbers of users with catalogue-like approaches to their Speckle data management. cc @paloknapo 

Where users have greater than 100 branches to a stream, these will be accessible online by URL at least until this may be supported. In connectors, you cannot reach your data. #2437 Suggests a further enhancement to DUI as a UX solution for many branches.

An alternative consideration is to have a "fetch more branches" button.

2023-07-19 08:33 UTC, teocomi commented
Closing as currently blocked by https://github.com/specklesystems/speckle-server/issues/1549 - will reopen/revisit when the right time comes.

2023-07-19 08:33 UTC, closed without merging