feat(AdvanceSteel): Mechanism to get main properties of native objects
specklesystems/speckle-sharp pull request #2444
Opened 2023-04-17 13:26 UTC by phliberato

## Description & motivation

## Changes:

- Mechanism(by reflection) to get main properties of native objects

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2023-04-18 16:13 UTC, AlanRynne requested changes
Haven't checked the actual code, but we're doing a repo-wide reformatting and cleanup and it seems some of your settings are conflicting with ours.

For formatting, we're using https://csharpier.com now (which is enforced by pre-commit hooks that are automatically installed).

If you wish to use Rider's Cleanup feature, we have a custom cleanup profile that you should set as the default for the repo (it should be already, but your settings may have overriden that)

2023-04-18 17:27 UTC, phliberato commented on Objects/Objects/BuiltElements/AdvanceSteel/AsteelBeam.cs
> +namespace Objects.BuiltElements.AdvanceSteel
Sorry Alan! When I was merging the branches, I thought it was a conflict error of git…. 😂

2023-04-18 17:29 UTC, phliberato commented on Objects/Objects/BuiltElements/AdvanceSteel/AsteelBeam.cs
> +namespace Objects.BuiltElements.AdvanceSteel
Could you fix this for me?

2023-04-18 18:20 UTC, AlanRynne commented on Objects/Objects/BuiltElements/AdvanceSteel/AsteelBeam.cs
> +namespace Objects.BuiltElements.AdvanceSteel
Yeah sorry about those conflicts, we should have told you about this incoming stuff, but we were still prepping the last details on our side!

I'll see if I can run a fix on this tomorrow

2023-07-17 17:05 UTC, teocomi commented
Hey @phliberato, apologies this got a bit forgotten, let us know if it's got to be merged in DEV for the 2.16 release :)

2023-07-17 17:50 UTC, phliberato commented
> Hey @phliberato, apologies this got a bit forgotten, let us know if it's got to be merged in DEV for the 2.16 release :)

Yes please.

2023-07-19 08:26 UTC, teocomi approved these changes

2023-07-19 08:26 UTC, teocomi approved these changes

2023-07-19 08:27 UTC, merged