feat(gh): First implementation of Flatten Collection
specklesystems/speckle-sharp pull request #2505
Opened 2023-05-02 05:44 UTC by AlanRynne

Adds a new "Flatten Collection" component to Grasshopper connector.

This component will accept a Speckle collection, and return a flat list of all speckle collections included within it (including itself).

To prevent any side-effects, the output collections are new objects that contain
- The elements inside that collection (but no inner collections)
- The original name of the collection and its type
- A dynamic property called "fullName" that contains all the names of all the parent collections and itself in Rhino style ("::" separator)

2023-05-09 21:52 UTC, teocomi requested changes
I'm getting some errors with a commit coming from Revit; maybe the data structure changed since this was written?

`1. Data conversion failed from Speckle Model to GH_SpeckleCollection`


Test commit: https://latest.speckle.dev/streams/ff85c554cc/commits/714d6e0a81
![image](https://github.com/specklesystems/speckle-sharp/assets/2679513/e0fea6bf-f2d9-40e4-9241-d5492c26afae)

2023-05-10 09:05 UTC, AlanRynne commented
This is due to the fact that `Model` does not currently inherit from `Collection`, and my logic in GH checks specifically to verify if an object is a `Collection` class, so this will fail and it is currently "by design".

Weirdly, your commit `Model` does contain all the info as if it were a collection (collectionType, name, elements list)

What I have improved is the text on the conversion error to be more understandable by a normal user.

![image](https://github.com/specklesystems/speckle-sharp/assets/2316535/03dcc4ea-2e99-4690-8564-b7bb3a9e8b24)

2023-05-10 09:37 UTC, AlanRynne commented
Scratch what I said, I was missing a commit from `dev` and a clean rebuild
<img width="776" alt="Screenshot 2023-05-10 at 11 36 14" src="https://github.com/specklesystems/speckle-sharp/assets/2316535/9cf6a461-c05c-4c11-8ccb-0b7b00aaddae">

2023-05-10 09:39 UTC, teocomi approved these changes

2023-05-10 09:54 UTC, merged