feat(revit): adds fallback option to receive displayable speckle objects as directshapes
specklesystems/speckle-sharp pull request #2841
Opened 2023-08-08 12:43 UTC by clairekuang

## Description & motivation

This feature includes the following:
- Fixes the `directshape receive setting` so that all commit objects are received as directshapes created from their displayValue geometry. This should look exactly as the commit does in the viewer.
- Changes the converter such that `CanConvertToNative()` returns `true` for any `Base` object with a `displayValue`
- Moves traversal of nested elements within conversion methods in the Converter, to the Connector receive binding. THis includes deprecation of the `SetHostedElements()` method in the Converter
- On failed element conversion in the Connector, retries receiving the element using the fallback DirectShape method by **temporarily toggling the user direct shape setting to true**

Closes #2777
Closes #2468

## Changes:

- Revit Connector and Converter
- 
## To-do before merge:

- [ ] More thorough testing of Revit receive workflows from different connectors, especially nested/hosted elements
- [ ] (opt) set fallback behavior as a setting, rather than use it by default

## Screenshots:

## Validation of changes:

Tested receiving large revit commits with instances using the directshape setting.

2023-08-09 12:08 UTC, teocomi commented on ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
> +            throw new Exception("Converting as Direct Shape");
Is there a better way to handle this than throwing?

2023-08-09 12:08 UTC, teocomi commented on ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
> +        converter.SetConverterSettings(displayableSettings);
Not sure it's a good UX to change this on their behalf, I'd rather just pass that in the report instead.

2023-08-10 14:17 UTC, teocomi commented on ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
> +      ApplicationObject ConvertObject(ApplicationObject obj, Base @base, Dictionary<string, string> displayableSettings)
Let's move local functions out

2023-08-10 15:03 UTC, teocomi commented on ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
> +        converter.SetConverterSettings(displayableSettings);
EDIT: let's add a new binding

2023-08-18 19:27 UTC, AlanRynne requested changes
Switching this to "requested changes" not because there's any changes pending on our side, but because I don't want to merge this without @connorivy express consent, as we've had to fix some rather complex conflicts on our side.

2023-08-22 22:06 UTC, connorivy reviewed
Made a small tweak and now I'm happy with the merge resolution

2023-08-22 22:07 UTC, connorivy approved these changes

2023-08-23 07:03 UTC, AlanRynne approved these changes
Amazing! Just browsed through your commit and looks great @connorivy.

Approving too in order to merge in 🥳

2023-08-23 07:17 UTC, AlanRynne commented on ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
> +      var fallbackMember = DefaultTraversal.displayValuePropAliases.Where(o => current[o] != null)?.First();
Done!

2023-08-23 08:16 UTC, merged