Fix(Revit) : Send area outlines separate from openings
specklesystems/speckle-sharp pull request #2996
Opened 2023-10-17 17:54 UTC by connorivy

## Description & motivation

Currently all analytical openings are baked inside the outline of the analytical element. This PR aims to separate the element outline from the element's openings. 

Instead of, for example, sending a wall with a door opening as 8-sided n-gon, we want to send it as a rectangle with the polyline representing the door opening in a separate property. The latter format is much easier for structural software to represent and is a more explicit definition of the object that the analytical element is representing.

## Changes:

- adds Element2DOutlineBuilder to facilitate removing the opening from the analytical outline
- extract some of the existing logic in the AnalyticalSurfaceToSpeckle method out into separate methods

## Screenshots:

Recieving in ETABS before
![image](https://github.com/specklesystems/speckle-sharp/assets/43247197/634dfa17-0979-4cbd-9830-36a7669ae541)

Receiving in ETABS after
![image](https://github.com/specklesystems/speckle-sharp/assets/43247197/9d69b205-baaf-4a2d-bbb7-018490e3985c)

## Validation of changes:

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2023-11-02 09:02 UTC, BovineOx reviewed
Ahh I think I need to click this big green button before anyone else can see. That makes sense :)

2023-11-02 09:05 UTC, AlanRynne commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/PointExtensions.cs
> +      double vectorAB_x = p1.x - p0.x;
We do! https://github.com/specklesystems/speckle-sharp/blob/0d17425151f5fe0e15b54ffb43b7ddcfd6695441/Objects/Objects/Geometry/Vector.cs#L210

2023-11-02 12:14 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/PointExtensions.cs
> +      double vectorAB_x = p1.x - p0.x;
What is the cost though of conversion pint to Vector, is that what we would want to do. It also poses another question as to whether points and vectors should co-exist, though technically not necessarily representing the same data typically they operate and are operated on in the same fashion.

2023-11-07 10:15 UTC, BovineOx requested changes
I think we should chat over some of the points just so I can ask a few Qs

2023-11-07 10:15 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/PointExtensions.cs
> +    public static bool IsOnLineBetweenPoints(this Point middle, Point p0, Point p1, double tolerance = .01)
We can worry about unit tests for the next issue

2023-11-07 10:15 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/PointExtensions.cs
> +      double vectorAB_x = p1.x - p0.x;
@AlanRynne we could probably discuss how easy it is to make use of the existing calcs

2023-11-07 10:15 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Models/Element2DOutlineBuilder.cs
> +      int insertIndex = indexToBeInserted == null ? outlinePoints.Count : indexToBeInserted.Value;
If you need the nullable, I think indexToBeInserted.HasValue than the null check might be easier to read but I'm not precious about it

2023-11-07 17:09 UTC, connorivy commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Models/Element2DOutlineBuilder.cs
> +          continue;
I made the change here, but we should have a clearer stance on this moving forward (avoid continues sometimes or always? Does the same apply to breaks?)

2023-11-08 19:04 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/PointExtensions.cs
> +      double vectorAB_x = p1.x - p0.x;
Let's discuss the quantities of these things because it would be more DRY to use the Vector math that already exists

2023-11-08 21:31 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/PointExtensions.cs
> +      double vectorAB_x = p1.x - p0.x;
So we will try this one converting the two points to vectors and re-using the Vector cross product to be more DRY, the numbers don't seem too scary...  we shall see

2023-11-08 21:34 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Models/Element2DOutlineBuilder.cs
> +  public readonly struct LineOverlappingOutlineData
If structs are small and used a lot copies are also pretty small and efficient, copying bytes is generally much faster than allocating them :) feel free to resolve

2023-11-08 21:34 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Models/Element2DOutlineBuilder.cs
> +      int insertIndex = indexToBeInserted == null ? outlinePoints.Count : indexToBeInserted.Value;
I think this is still a recommendation but your choice

2023-11-09 11:15 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Models/Element2DOutlineBuilder.cs
> +    static IEnumerable<Line> EnumeratePolyline(Polyline polyline)
Could equally be IEnumerable but that might be a bigger task tbh

2023-11-09 11:22 UTC, BovineOx commented on Objects/Converters/ConverterRevit/ConverterRevitShared/Models/Element2DOutlineBuilder.cs
> +    static IEnumerable<Line> EnumeratePolyline(Polyline polyline)
Let's just do the extension for speed and give us time to consider the IEnemurable option

2023-11-09 15:51 UTC, BovineOx approved these changes

2023-11-09 15:53 UTC, merged