gergo/defaultContextView
specklesystems/speckle-sharp pull request #3037
Opened 2023-11-11 14:31 UTC by gjedlicska

- chore(CSI): Run CSharpier on all CSI related projects (#2947)
- chore(core): Make client functions consistent with cancellation token position (#2925)
- chore(core): Removed override ErrorsAsWarnings category (#2949)
- Implemented Traversal Refactor for CSI connectors (#2961)
- feat(revit): Support for TopoSolid (#2951)
- Feat(ETABS) : receive gridlines (#2969)
- fix(rvt): Fixes curve extraction method for Ceilings and Floors (#2973)
- fix(rhino): default to using speckle id when creating render materials with no name (#2974)
- feat(autocad/rhino): adds gridline to native conversion (#2963)
- feat(Archicad, Revit): Room height (#2977)
- feat: check if server is using fe2 (#2989)
- feat(core): Adds SpeckleLogConfig input to Setup.Initialize (#2994)
- fix(CSI): Fixes missing materials on receive (#2988)
- feat(dui): better fe2 compatibility (#2991)
- feat(automate): New Automate SDK (#2980)
- fix(core): Fixed regression with stream collaborators query parameters (#3000)
- Csharpier CSI (#2999)
- feat(batchUploader): Batchuploader Client (#2967)
- feat: Updates Automate.SDK with new API changes (#3004)
- feat (Revit, Archicad): Support grids between Revit and Archicad (#2990)
- fix(automate): Adds return code to automate Runner (#3011)
- enhancement(csi): CSI converter error handling and logging (#2970)
- chore(objects): corrected nullability to objects in structural namespace (#3009)
- chore(dev): Remove CRL check from proxy client (#3025)
- log(structral): Unified logging between structural connectors (#3024)
- feat(Archicad): Send and receive layer information (#3013)
- feat (Archicad, Revit): Speckle Levels (#3012)
- feat(Archicad): Collections support (#3014)
- Performance(csi) : commit database tables in single transaction (#2998)
- feat(objects/revit): new `RebarGroup` class and `RebarToSpeckle` conversion in Revit (#3023)
- chore(CSI): added exception for failing areas and frames (#3029)
- Create Archicad levels based on elevation (#3031)
- Fix(Revit) : Send area outlines separate from openings (#2996)
- Feat(CSi) : Improved analytical results (#3028)
- Fix(Revit) : add material quantites by mesh (#3030)
- fix(archicad): Archicad nullable levels fix (#3032)
- Fixing removed elses
- feat: changes the default server URL (#3033)
- fix(Archicad): Crash when sending a Corner Window (#3034)
- fix(csi): Fix settings throwing  (#3035)
- fix(core): Fixes Branch get Limit up to 500 (#3036)
- feat: add default context view reporting

## Description & motivation

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2023-11-12 10:47 UTC, teocomi requested changes
Sure this is the right PR?

👀👀👀 +10,703 −4,172

2023-11-13 08:15 UTC, gjedlicska commented
> Sure this is the right PR?
> 
> 👀👀👀 +10,703 −4,172

Wrong target branch :D

2023-11-13 20:26 UTC, AlanRynne approved these changes
🪄 🙌🏼 Merging this in.

2023-11-13 22:41 UTC, teocomi approved these changes

2023-11-14 08:38 UTC, merged