Cnx 9241 define a unit of work pattern for our dependency injection related to scoped factory
specklesystems/speckle-sharp pull request #3276
Opened 2024-04-10 20:30 UTC by BovineOx

- New UnitOfWork, Factory and associated interfaces
- The UoW can be used as follows:

`
// inject the factory
private readonly IUnitOfWorkFactory _unitOfWorkFactory;

// resolve an interface that represents the unit of work
// this is to say that there will be a root object that can be resolved from the factory
// and all if the dependencies that should be unique per lifetime, will be created as distinct instances
// for each call to Resolve() - naturally the type you want needs to be provided, i.e.
using ISpeckleConverterToSpeckle toSpeckle = _unitOfWorkFactory.Resolve<ISpeckleConverterToSpeckle>();

// note that this returns a IUnitOfWork (concrete type UnitOfWork) this wraps
// the service and the ILifetimeScope AND when the UoW is disposed, it disposes the newly created ILifetimeScope

`
**NOTE:**
We should probably be injecting this into the SendBinding and the UOW should create whatever the root object should be. This might end up being the same type each Connector, which would be ideal.

Note also that Revit and the other converters seem to differ as to which thing is the UoW and we should probably address this.

2024-04-11 11:49 UTC, JR-Morgan requested changes

2024-04-12 09:34 UTC, AlanRynne requested changes
My only feedback would be that we may want to separate the `UnitOfWork` and the resolved service into 2 different things.

- The unit of work factory should have a `BeginUoW` that returns a `UnitOfWork` object holding the child lifetime scope.
- `UnitOfWork` should be the one with the `Resolve` method.

This way we abstract the intention of that unit of work from its initial declaration. But also I may be understanding things slightly off here :)

2024-04-16 09:36 UTC, BovineOx commented on DUI3-DX/Connectors/Revit/Speckle.Connectors.Revit2023/log20240410.txt
Nope!

2024-04-16 09:36 UTC, BovineOx commented on DUI3-DX/Sdk/Speckle.Autofac/DependencyInjection/IScopedFactory._cs
Good point!

2024-04-16 09:37 UTC, BovineOx commented on Core/Core/Logging/Setup.cs
> +    // SpeckleLog.Initialize(hostApplication, versionedHostApplication, logConfiguration);
I can show you I imagine, it was a sentry explosion, but it could be because I had stop on all exceptions at the time

2024-04-16 19:22 UTC, AlanRynne approved these changes

2024-04-16 19:36 UTC, JR-Morgan approved these changes
The comments I've raised appear to be resolved

2024-04-16 19:40 UTC, merged