chore(dui3): adds test bindings + a poc simple config binding
specklesystems/speckle-sharp pull request #3284
Opened 2024-04-16 10:32 UTC by didimitrie

Adds test bindings back + poc config binding
Tested in:
- Rhino 7
- Autocad
Not tested in (probably not needed, if any breakage it should be easily fly-by fixed later):
- ArcGIS
- Revit

2024-04-16 10:37 UTC, didimitrie commented
Pair PR in server: https://github.com/specklesystems/speckle-server/pull/2209 > Note, without this merged the config changes will not work and the UI might go full red in the console.

2024-04-17 12:35 UTC, BovineOx requested changes
Mostly just adding the POC comment tbh

2024-04-17 12:35 UTC, BovineOx commented on DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/DependencyInjection/AutofacArcGISModule.cs
> +    builder.RegisterType<ConfigBinding>().As<IBinding>().SingleInstance().WithParameter("connectorName", "ArcGIS"); // POC: Easier like this for now, should be cleaned up later
I don't have too strong feeling about this, but arguable there may be a ArcGISContext that already has this string or could have it... certainly can live for a bit with the POC comment

2024-04-17 12:35 UTC, BovineOx commented on DUI3-DX/DUI3/Speckle.Connectors.DUI/Bindings/ConfigBinding.cs
> +    ConfigStorage = new SQLiteTransport(scope: "DUI3Config");
Can this be injected yet? If not let's add a POC comment

2024-04-18 11:54 UTC, BovineOx approved these changes

2024-04-18 13:17 UTC, AlanRynne approved these changes
Looks good, but can we verify the settings are working right?

Should I expect "light mode" to be preserved in Rhino across restarts?

2024-04-18 13:17 UTC, AlanRynne commented on DUI3-DX/DUI3/Speckle.Connectors.DUI/Bindings/ConfigBinding.cs
> +  public bool DarkTheme { get; set; } = true;
Unacceptable default 🤣

2024-04-18 13:17 UTC, AlanRynne commented on DUI3-DX/DUI3/Speckle.Connectors.DUI/Bindings/ConfigBinding.cs
> +/// </summary>
I'm not sure this is storing as it should, mine always starts in dark mode even after switching it.

2024-04-18 16:00 UTC, merged