CNX-9226 revit column to Speckle
specklesystems/speckle-sharp pull request #3308
Opened 2024-04-23 21:59 UTC by connorivy

## Description & motivation

Most of the column conversion was already here. However, I've made it a bit clearer by extracting out the baseCurve property (which is incorrectly named BaseLine...) calculation into its own method. Also quickly looked into a few things that didn't quite make sense about the way we are currently sending columns. If I could resolve it, then I did, and if not then I added a POC comment.

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-04-25 12:04 UTC, BovineOx approved these changes

2024-04-25 13:02 UTC, AlanRynne requested changes
Just one change regarding the `DB.` and `SOBR.` prefixes.

Ideally we should keep it to 1 standard, I would vote for the prefixes but happy to hear other opinions 🙂

2024-04-25 13:02 UTC, AlanRynne commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FamilyInstanceConversionToSpeckle.cs
> +    if (
I guess this was something regarding analytical columns maybe? 

I would say that if we don't know why a piece of code was there; and it also doesn't seem to reflect our intent... lets just keep whatever makes sense (in this case it would be OST_Columns I guess).

Right now I would rather a conversion fail or not work than to have some weird side-effect happening that we were not aware of.

2024-04-25 13:04 UTC, AlanRynne commented
Also, CI fails ❌

2024-04-25 16:19 UTC, connorivy commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/ColumnConversionToSpeckle.cs
> -  private readonly IRawConversion<DB.Level, SOBR.RevitLevel> _levelConverter;
I definitely agree with this. The downside is that, currently, if you are just adding the prefix for clarity then you will get IDE0001 warnings that the "name can be simplified". And this warning will eventually throw an error in the CI. What do you think about ignoring this warning for CI errors?

2024-04-25 16:23 UTC, connorivy commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/ColumnConversionToSpeckle.cs
> -  private readonly IRawConversion<DB.Level, SOBR.RevitLevel> _levelConverter;
Oh wait I see; you're saying to not import the namespaces at all. So, every occurrence of Speckle and Autodesk types MUST be prefixed. That could get a bit tedious, but I do also see the value of that as well

2024-04-29 07:57 UTC, AlanRynne approved these changes

2024-04-29 08:02 UTC, merged