Cnx 9230 revit wall
specklesystems/speckle-sharp pull request #3322
Opened 2024-04-29 21:39 UTC by connorivy

## Description & motivation

Adds the wall conversion. Specifically consolidated the existing logic into more digestible methods and added functionality to send curtain walls and stacked walls that didn't previously exist.

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

Here is a working curtain wall sent with this conversion https://latest.speckle.dev/streams/85bc4f61c6/commits/49bc3fe387. You'll notice that you cannot select the entire wall, only the individual panels, but this was existing behavior.

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

2024-04-30 12:24 UTC, AlanRynne approved these changes
I see no blockers but I left a comment for @BovineOx to look at 😉

2024-04-30 12:24 UTC, AlanRynne commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Extensions/ElementExtensions.cs
> +          BuiltInCategory.OST_WeakDims
I'm assuming these have been ported from the original logic. I'd be curious to know if there is any others we should include here.

2024-04-30 12:24 UTC, AlanRynne commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/CurveArrArrayToSpecklePolycurveConverter.cs
> +  }
hahaha autodesk APIs... 🤮

2024-04-30 12:24 UTC, AlanRynne commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/RevitConverterToSpeckle.cs
> +  }
ohhh, is this trying to resolve the converter including all parent type converters?

Neat! @BovineOx this is not a bad idea... could this be somehow moved into the default resolving logic or some new function of the converter (`ResolveInstance` and `ResolveInstanceWithInheritance`? name pending)

2024-04-30 12:24 UTC, AlanRynne commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/WallConversionToSpeckle.cs
> +      speckleWall["voids"] = polycurves.Skip(1);
We know for a fact many times these are not even `voids`... 😅 we really should re-evaluate the whole wall conversions in revit to account for sketched walls properly

2024-04-30 12:45 UTC, connorivy commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/WallConversionToSpeckle.cs
> +      speckleWall["voids"] = polycurves.Skip(1);
I agree. We also need to stop using dynamic properties (in my opinion)

2024-04-30 12:47 UTC, AlanRynne commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/WallConversionToSpeckle.cs
> +      speckleWall["voids"] = polycurves.Skip(1);
YES!! 🙌🏼 you've got my vote and @JR-Morgan's hahah

2024-04-30 13:49 UTC, BovineOx requested changes
Mostly just adding comments and a couple of tickets

2024-04-30 13:49 UTC, BovineOx commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/RevitConverterToSpeckle.cs
> +  }
Yeah it needs some thought, maybe add a POC: comment to consider making this more accessible as a pattern - make a CNX and add it here

2024-04-30 13:49 UTC, BovineOx commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/WallConversionToSpeckle.cs
> +      speckleWall["voids"] = polycurves.Skip(1);
Can w add a ticket to review "re-evaluate the whole wall conversions in revit to account for sketched walls properly" and drop the CNX here plz?

2024-04-30 13:49 UTC, BovineOx commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/HostedElementConversionToSpeckle.cs
> +    return GetHostedElementsConvertedFromIds(host, host.GetHostedElementIds());
Hosted elements were kind of OOS for Alpha so maybe this is fine for now but I think @clairekuang needs to be across this for other object relationships such as blocks, instancing etc...

Maybe add a POC: comment for now to the effect of, needs to be reviewed

2024-05-02 14:33 UTC, AlanRynne approved these changes

2024-05-02 14:34 UTC, merged