Cnx 9227 send floors from Revit
specklesystems/speckle-sharp pull request #3346
Opened 2024-05-02 21:53 UTC by connorivy

## Description & motivation

Adds floor converter. See this commit https://latest.speckle.systems/projects/85bc4f61c6/models/6cd9058fba for examples of the send behavior

2024-05-02 22:05 UTC, BovineOx requested changes
Just some minor requests for + comments. I am presuming we copy and pasted most of this across as is? Main thing is to be in the habit of interfacing out new classes we plan to inject so we have loose coupling and not tight. When we look to do unit and integration tests we'll have an easier time if we've done this.

2024-05-02 22:05 UTC, BovineOx commented on DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.DependencyInjection/AutofacRevitConverterModule.cs
> +    builder.RegisterType<SlopeArrowExtractor>().AsSelf().InstancePerLifetimeScope();
Can you add an interface for this to avoid adding more tight coupling

2024-05-02 22:05 UTC, BovineOx commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FloorConversionToSpeckle.cs
> +    // POC: https://spockle.atlassian.net/browse/CNX-9396
Might be good to just add a comment as to what the ticket relates to, just a 1 liner for context

2024-05-02 22:05 UTC, BovineOx commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FloorConversionToSpeckle.cs
> +    if (profiles.Count > 1)
can we have a linespace between

2024-05-03 09:28 UTC, AlanRynne approved these changes
Just addressed Ians comments, waiting for CI

2024-05-03 09:58 UTC, merged