Revit/connor/silence duplicate conversions
specklesystems/speckle-sharp pull request #3357
Opened 2024-05-03 20:48 UTC by connorivy

## Description & motivation

Sometimes multiple objects in revit can host the same sub element. In our current connector, we are just converting these items multiple times. However, in this connector an exception is being thrown. For now, I am just silencing this exception until we can address the issue more completely https://spockle.atlassian.net/browse/CNX-9402.

I also made a change to make the "TryGetValueAsDocumentObject" safer

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-05-03 21:02 UTC, JR-Morgan approved these changes

2024-05-06 08:35 UTC, AlanRynne requested changes
Valid solution, but I think it's being done in the wrong place (see comment). Happy to discuss more.

2024-05-06 08:35 UTC, AlanRynne commented on DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/RevitConverterToSpeckle.cs
> +      }
Why aren't we just coding the cache to not explode?

Something like `HasConvertedBase()` or refactor `AddConvertedBase()` to return true if it succeeds to add the object to the cache?

We're also using `Add` in the cache super naively, assuming an object will never be set beforehand, but this PR's existence means that this assumption is not correct.

I would argue this is not the right fix, and instead the cache should be made less easy to explode (it is a cache after all, which should be a utility thing that doesn't really need to exist to perform the main logic correctly)

2024-05-06 10:50 UTC, AlanRynne approved these changes
Discussed with Ian and Jedd. We're merging this in and adding a ticket to re-visit hosted element conversion and caching.

2024-05-06 11:12 UTC, merged