Add more null checks for Revit
specklesystems/speckle-sharp pull request #3425
Opened 2024-05-17 08:04 UTC by adamhathcock

2024-05-17 13:39 UTC, JR-Morgan requested changes

2024-05-17 13:39 UTC, JR-Morgan commented on DUI3-DX/Sdk/Speckle.Autofac/AssemblyResolver.cs
> +    // POC: dupe code
no longer duped

2024-05-17 13:48 UTC, adamhathcock commented on DUI3-DX/Sdk/Speckle.Autofac/AssemblyResolver.cs
> +    // POC: dupe code
changed

2024-05-20 11:18 UTC, JR-Morgan approved these changes

2024-05-20 11:46 UTC, merged