enable lock files for dui3
specklesystems/speckle-sharp pull request #3510
Opened 2024-06-14 12:17 UTC by adamhathcock

enable nuget lock files for dui3

- this will allow us to better monitor change in dependencies
- use lock files for restoration for repeatable builds
- cache nuget and restore for faster builds

2024-06-14 12:47 UTC, AlanRynne requested changes
I think we should also modify the CI to run in locked mode since we're at it

2024-06-20 08:41 UTC, AlanRynne commented on .github/workflows/ci.yml
> +    runs-on: windows-latest
💔

2024-06-20 08:41 UTC, AlanRynne commented on .github/workflows/main.yml
> +        run: echo "version=${{ env.GitVersion_FullSemVer }}" >> "$GITHUB_OUTPUT"
Why the copy/paste? reusable workflows are ♥️
If we need some variation we can add inputs to it.

2024-06-20 08:41 UTC, AlanRynne commented on .github/workflows/main.yml
> +    runs-on: windows-latest
This doesn't need to be windows at all 🙂

2024-06-20 09:00 UTC, AlanRynne approved these changes

2024-06-20 09:00 UTC, merged

2024-06-20 10:29 UTC, adamhathcock commented
For https://spockle.atlassian.net/browse/DUI3-311

2024-06-20 10:30 UTC, adamhathcock commented
DUI3-311