D ui3 305 agis implement highlight for individual features e.g. from receive report
specklesystems/speckle-sharp pull request #3529
Opened 2024-06-21 12:53 UTC by KatKatKateryna

1. Introduce struct holding LayerURI (represented as string because this is how native API is treating LayersURI), featureId, MapMember (actual layer object on the map)
2. Adapt Report building and Highlight functionality to use this instead of flat string with LayerURI
3. Add functionality to select individual features if FeatureID is available

2024-06-27 11:26 UTC, oguzhankoral requested changes
Overall, I liked the extraction on object id which was always confusing for me, maybe I'm greedy but I believe we have an opportunity to have it more clean way. Then good to go 🚀

2024-06-27 11:26 UTC, oguzhankoral commented on DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Utils/ObjectID.cs
> +public struct ObjectID
I would omit MapMember from this struct, it is confusing why objectID checks for MapMember as below. 

```c#
if (objectId.MapMember == null)
{
   continue;
}
``` 

What I expect from `ObjectID` is just id, if you include MapMember it becomes something else. In this case, we might need another struct that has MapMember too instead considering its nullability on `ObjectID` struct.

2024-06-28 17:33 UTC, KatKatKateryna commented
converting to draft to update documentation

2024-07-01 10:41 UTC, oguzhankoral approved these changes
Tested and LGTM 🚀

2024-07-01 10:44 UTC, merged